### ISSUE TITLE
Displacement files not loading in the correct order

### ISSUE THREAD

**Issue by jc14269** [mcsloy/NanoVerNemdParser#1]
In the "trajectory_generator.py" file the files are read in using

```python
def auto_load_displacement_frames(path: str) -> list[NemdDisplacementFrame]:
    """Convenience function for parsing loading of displacement frame files.

    When provided with a path to a directory, this function will locate all files
    of the form "average_xyz_displacement_*ps". Matching files will be parsed
    into a list of `NemdDisplacementFrame` entities. Note that displacement frames
    will be sorted in chronological order according to the timestep specified
    in their file names.

    Arguments:
        path: the path to the directory within which the displacement data files
            are all stored.

    Returns:
        displacement_frames: a chronologically sorted list of displacement frames.
    """
    # Locate all files matching the expression "average_xyz_displacement_*ps"
    # where "*" is the time elapsed.
    files = glob.glob(join(path, "average_xyz_displacement_*ps"))

   
    # Sort the file list so that frames will be in chronological order
    pattern = re.compile(r'(?<=average_xyz_displacement_)\d*(?=ps)')
    files.sort(key=lambda i: int(pattern.search(i).group(0)))

    # Parse the files into displacement frame entities
    displacement_frames = list(map(NemdDisplacementFrame.load, files))

    # Return the displacement frame list
    return displacement_frames
```

I found that my files were being read in a weird order, it was reading them in the order;
  average_displacement_0ps
  average_displacement_1000ps
  average_displacement_100ps
  average_displacement_1010ps
  average_displacement_1020ps
  e.t.c

I added a function that I defined before the previous function 
```python
def natural_sort_key(s):
    return [int(c) if c.isdigit() else c.lower() for c in re.split(r'(\d+)', s)]
```
and sorted the files this way, I think this fixed the issue

**Comment by mcsloy** [comment]
This is rather odd. The order you have shown is what you would expect if you tried to sort the file names, or the numbers contained within them, as strings rather than integers. It looks almost if the `int` function in `files.sort(key=lambda i: int(pattern.search(i).group(0)))` has been removed. Furthermore, the file names you provided do not exactly match the anticipated format; i.e. they are missing the `_xyz_` component of the name. However, this would just result in a hard error rather than an incorrectly ordered list. Please provide me with the full list of file names; and the order into which they get sorted. Could you also send me your modified version of the `auto_load_displacement_frames` function as well please.  This way I can take a deeper look at the issue. Thanks

**Comment by jc14269** [comment]
All sorted, thanks again!
